name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.8.3
          virtualenvs-create: true
          virtualenvs-in-project: true
          
      - name: Install dependencies
        run: poetry install --no-interaction
        
      - name: Add linting tools
        run: poetry add --group dev flake8 black isort mypy bandit
        
      - name: Run linters
        run: |
          poetry run black --check src/
          poetry run isort --check-only --profile black src/
          poetry run bandit -r src/ -c pyproject.toml
