name: Publish to PyPI

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
      # Add contents read permission to access the repository
      contents: read
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
          
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.8.3
          virtualenvs-create: true
          virtualenvs-in-project: true
          
      - name: Install dependencies
        run: poetry install --no-interaction
        
      - name: Build package
        run: poetry build
        
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1.12
        # No need to specify username/password as this uses OpenID Connect
        # for trusted publisher authentication